// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drdjhcnuvdjzijncyocg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyZGpoY251dmRqemlqbmN5b2NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDY1MjEsImV4cCI6MjA2NTQ4MjUyMX0.1G_iZ83Hg5JJszXaDn6iN8gnGWkiilHZYa-Pc4OP6Ys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);